---
- hosts: local
  gather_facts: no
  connection: local

  tasks:
  - name: OBTAIN LOGIN CREDENTIALS
    include_vars: secrets.yaml

  - name: DEFINE PROVIDER
    set_fact:
      provider:
        host: "{{ inventory_hostname }}"
        username: "{{ creds['username'] }}"
        password: "{{ creds['password'] }}"
        auth_pass: "{{ creds['auth_pass'] }}"

  - name: SHOW RUN | BEG BANNER
    ios_command:
      provider: "{{ provider }}"
      authorize: yes
      commands:
        - show run | beg banner
        - show run | i hostname
        - show  ip interfaces brief
    tags: show
    register: banner

  - debug: var=banner.stdout_lines

  - name: CREATE NEW BANNER
    ios_config:
      provider: "{{ provider }}"
      authorize: yes
      lines:
        - banner motd ^Welcome to RAS AUTOMATION^

  - name: SHOW RUN | BEG BANNER
    ios_command:
      provider: "{{ provider }}"
      authorize: yes
      commands:
        - show run | beg banner
    register: banner

  - debug: var=banner.stdout_lines
