---
- name: Audit 
  hosts: all
  connection: network_cli
  gather_facts: false
  
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
    ansible_command_timeout: 60
    ansbile_connection: "network_cli"
    ansible_network_os: "ios"

  tasks:

    - name: Accespt ansible net hostname
      ios_facts:
        gather_subset: min
        
        
    - name: run audit on remote devices
      ios_command:
          commands:
          - show run | i hostname
          - show version
          - show interfaces
          - show run | section ntp
          - show run | section logging
          - show run | section vty
          - show run | section aaa
          - show run | section snmp
          - show run | section domain
          - show run | section username
          #- show interface status | i down
      tags: show
      register: output
    - name: run show version and check to see if output contains IOS
      ios_command:
          commands: show version
          wait_for: result[0] contains IOS
      register: output
          
    - name: sh run
      ios_config:
          #commands: show run | i line
      #register: output

    - name: print output
      debug:
        var: output

 
