- hosts: all
  
  
  gather_facts: no
  connection: local
  
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
    ansible_connection: network_cli
    ansible_network_os: cisco.ios.ios
    
  tasks:
  - name: OBTAIN LOGIN CREDENTIALS
    include_vars: secrets.yaml

  - name: DEFINE PROVIDER
    set_fact:
      provider:
        host: "{{ inventory_hostname }}"
        username: "{{ creds['username'] }}"
        password: "{{ creds['password'] }}"
        auth_pass: "{{ creds['auth_pass'] }}"

  - name: SHOW RUN | I SSH
    ios_command:
      provider: "{{ provider }}"
      authorize: yes
      commands:
        - show run | i ssh
    register: before_v2
 
  - debug: var=before_v2.stdout_lines
 
  - name: IP SSH VERSION 2
    ios_config:
      provider: "{{ provider }}"
      authorize: yes
      lines:
        - ip ssh version 2

 
  - name: SHOW RUN | I SSH
    ios_command:
      provider: "{{ provider }}"
      authorize: yes
      commands:
        - show run | i ssh
    register: after_v2
 
  - debug: var=after_v2.stdout_lines
