#Cisco IOS SNMP Playbook
#Check out my website www.thenetwork.engineer

- hosts: all
  vars:
    ansible_python_interpreter: "/usr/bin/python3"

  gather_facts: no
  connection: local

  tasks:
  - name: OBTAIN LOGIN CREDENTIALS
    include_vars: secrets.yaml

  - name: DEFINE PROVIDER
    set_fact:
      provider:
        host: "{{ inventory_hostname }}"
        username: "{{ creds['username'] }}"
        password: "{{ creds['password'] }}"
        auth_pass: "{{ creds['auth_pass'] }}"

  - name: SHOW RUN | INC SNMP
    ios_command:
      provider: "{{ provider }}"
      authorize: yes
      commands:
        - show run | i snmp
    register: before_snmp
 
  - debug: var=before_snmp.stdout_lines
 
  - name: SET COMMUNITY STRING
    ios_config:
      provider: "{{ provider }}"
      authorize: yes
      lines:
        - snmp-server community thenetwork.engineer

  - name: TRAP-SOURCE LOOPBACK0
    ios_config:
      provider: "{{ provider }}"
      authorize: yes
      lines:
         - int lo0
         - snmp-server trap-source Loopback0

  - name: SET CONTACT INFO
    ios_config:
      provider: "{{ provider }}"
      authorize: yes
      lines:
        - snmp-server contact colin@thenetwork.engineer

  - name: ENABLE TRAPS
    ios_config:
      provider: "{{ provider }}"
      authorize: yes
      lines:
        - snmp-server enable traps ospf state-change
        - snmp-server enable traps ospf errors
        - snmp-server enable traps ospf retransmit
        - snmp-server enable traps ospf lsa
        - snmp-server enable traps ospf cisco-specific errors
        - snmp-server enable traps ospf cisco-specific retransmit
        - snmp-server enable traps ospf cisco-specific lsa


  - name: SET SNMP SERVER ADDRESS 
    ios_config:
      provider: "{{ provider }}"
      authorize: yes
      lines:
        - snmp-server host 192.168.161.25 pwdhere


  - name: SHOW RUN | INC SNMP
    ios_command:
      provider: "{{ provider }}"
      authorize: yes
      commands:
        - show run | i snmp
    register: after_snmp
 
  - debug: var=after_snmp.stdout_lines
